export const hospitals = [
  // Đà Nẵng
  {
    label: 'Bệnh viện C Đà Nẵng',
    value: '48001',
    city: 'Đà Nẵng',
    type: 'Công lập',
    level: 'Trung ương',
  },
  {
    label: 'Bệnh viện Đa khoa Đà Nẵng',
    value: '48002',
    city: 'Đà Nẵng',
    type: 'Công lập',
    level: 'Tỉnh',
  },
  {
    label: 'Bệnh viện Phụ sản - Nhi Đà Nẵng',
    value: '48003',
    city: 'Đà Nẵng',
    type: 'Công lập',
    level: 'Tỉnh',
  },
  {
    label: 'Bệnh viện Ung Bướu Đà Nẵng',
    value: '48011',
    city: 'Đà Nẵng',
    type: 'Công lập',
    level: 'Tỉnh',
  },
  {
    label: 'Bệnh viện Đa khoa Quốc tế Vinmec Đà Nẵng',
    value: 'PROV_3001',
    city: 'Đà Nẵng',
    type: 'Tư nhân',
    level: 'N/A',
  },
  {
    label: 'Bệnh viện Đa khoa Hoàn Mỹ Đà Nẵng',
    value: '48005',
    city: 'Đà Nẵng',
    type: 'Tư nhân',
    level: 'N/A',
  },
  {
    label: 'Bệnh viện Đa khoa Gia Đình',
    value: 'PROV_3002',
    city: 'Đà Nẵng',
    type: 'Tư nhân',
    level: 'N/A',
  },

  // TP. Hồ Chí Minh
  {
    label: 'Bệnh viện Nhân dân 115',
    value: '79015',
    city: 'TP. Hồ Chí Minh',
    type: 'Công lập',
    level: 'Tỉnh',
  },
  {
    label: 'Bệnh viện Nhân dân Gia Định',
    value: '79014',
    city: 'TP. Hồ Chí Minh',
    type: 'Công lập',
    level: 'Tỉnh',
  },
  {
    label: 'Bệnh viện Từ Dũ',
    value: '79023',
    city: 'TP. Hồ Chí Minh',
    type: 'Công lập',
    level: 'Tỉnh',
  },
  {
    label: 'Bệnh viện Nhi Đồng 1',
    value: '79025',
    city: 'TP. Hồ Chí Minh',
    type: 'Công lập',
    level: 'Tỉnh',
  },
  {
    label: 'Bệnh viện Ung Bướu',
    value: '79024',
    city: 'TP. Hồ Chí Minh',
    type: 'Công lập',
    level: 'Tỉnh',
  },
  {
    label: 'Bệnh viện huyện Bình Chánh',
    value: '79038',
    city: 'TP. Hồ Chí Minh',
    type: 'Công lập',
    level: 'Huyện',
  },
  {
    label: 'Bệnh viện FV (Pháp - Việt)',
    value: 'PROV_2001',
    city: 'TP. Hồ Chí Minh',
    type: 'Tư nhân',
    level: 'N/A',
  },
  {
    label: 'Bệnh viện Đa khoa Hoàn Mỹ Sài Gòn',
    value: '79071',
    city: 'TP. Hồ Chí Minh',
    type: 'Tư nhân',
    level: 'N/A',
  },
  {
    label: 'Bệnh viện Đa khoa Tâm Anh TP. HCM',
    value: 'PROV_2002',
    city: 'TP. Hồ Chí Minh',
    type: 'Tư nhân',
    level: 'N/A',
  },
  {
    label: 'Bệnh viện Đa khoa Quốc tế Vinmec Central Park',
    value: '79483',
    city: 'TP. Hồ Chí Minh',
    type: 'Tư nhân',
    level: 'N/A',
  },

  // Hà Nội
  {
    label: 'Bệnh viện Đa khoa Xanh Pôn',
    value: '1004',
    city: 'Hà Nội',
    type: 'Công lập',
    level: 'Tỉnh',
  },
  { label: 'Bệnh viện Thanh Nhàn', value: '1006', city: 'Hà Nội', type: 'Công lập', level: 'Tỉnh' },
  {
    label: 'Bệnh viện Đa khoa Đống Đa',
    value: '1004',
    city: 'Hà Nội',
    type: 'Công lập',
    level: 'Tỉnh',
  },
  {
    label: 'Bệnh viện Đa khoa Hà Đông',
    value: '3001',
    city: 'Hà Nội',
    type: 'Công lập',
    level: 'Tỉnh',
  },
  {
    label: 'Bệnh viện Đa khoa Quốc tế Vinmec Times City',
    value: 'PROV_1001',
    city: 'Hà Nội',
    type: 'Tư nhân',
    level: 'N/A',
  },
  {
    label: 'Bệnh viện Đa khoa Quốc tế Thu Cúc',
    value: 'PROV_1002',
    city: 'Hà Nội',
    type: 'Tư nhân',
    level: 'N/A',
  },
  {
    label: 'Bệnh viện Đa khoa Hồng Ngọc',
    value: 'PROV_1003',
    city: 'Hà Nội',
    type: 'Tư nhân',
    level: 'N/A',
  },
  {
    label: 'Bệnh viện Đa khoa Tâm Anh Hà Nội',
    value: 'PROV_1004',
    city: 'Hà Nội',
    type: 'Tư nhân',
    level: 'N/A',
  },

  // Tuyến Trung ương / Bộ ngành
  {
    label: 'Bệnh viện Bạch Mai',
    value: '1002',
    city: 'Hà Nội',
    type: 'Bộ Y tế',
    level: 'Trung ương',
  },
  {
    label: 'Bệnh viện Chợ Rẫy',
    value: '79000',
    city: 'TP. Hồ Chí Minh',
    type: 'Bộ Y tế',
    level: 'Trung ương',
  },
  {
    label: 'Bệnh viện Trung ương Huế',
    value: '46001',
    city: 'Thừa Thiên Huế',
    type: 'Bộ Y tế',
    level: 'Trung ương',
  },
  {
    label: 'Bệnh viện Hữu nghị Việt Đức',
    value: '1003',
    city: 'Hà Nội',
    type: 'Bộ Y tế',
    level: 'Trung ương',
  },
  {
    label: 'Bệnh viện Trung ương Quân đội 108',
    value: '1014',
    city: 'Hà Nội',
    type: 'Bộ Quốc phòng',
    level: 'Trung ương',
  },
  {
    label: 'Bệnh viện Nhi Trung ương',
    value: '1008',
    city: 'Hà Nội',
    type: 'Bộ Y tế',
    level: 'Trung ương',
  },
  {
    label: 'Bệnh viện Phụ sản Trung ương',
    value: '1007',
    city: 'Hà Nội',
    type: 'Bộ Y tế',
    level: 'Trung ương',
  },
  { label: 'Bệnh viện K', value: '1906', city: 'Hà Nội', type: 'Bộ Y tế', level: 'Trung ương' },
  { label: 'Bệnh viện E', value: '1010', city: 'Hà Nội', type: 'Bộ Y tế', level: 'Trung ương' },
  {
    label: 'Bệnh viện Bệnh Nhiệt đới Trung ương',
    value: '1057',
    city: 'Hà Nội',
    type: 'Bộ Y tế',
    level: 'Trung ương',
  },
  {
    label: 'Bệnh viện Lão khoa Trung ương',
    value: '1925',
    city: 'Hà Nội',
    type: 'Bộ Y tế',
    level: 'Trung ương',
  },
  {
    label: 'Bệnh viện Mắt Trung ương',
    value: '1011',
    city: 'Hà Nội',
    type: 'Bộ Y tế',
    level: 'Trung ương',
  },
  {
    label: 'Bệnh viện Răng Hàm Mặt Trung ương Hà Nội',
    value: '1006',
    city: 'Hà Nội',
    type: 'Bộ Y tế',
    level: 'Trung ương',
  },
  {
    label: 'Bệnh viện Tai Mũi Họng Trung ương',
    value: '1009',
    city: 'Hà Nội',
    type: 'Bộ Y tế',
    level: 'Trung ương',
  },
  {
    label: 'Bệnh viện Y học cổ truyền Trung ương',
    value: '1013',
    city: 'Hà Nội',
    type: 'Bộ Y tế',
    level: 'Trung ương',
  },
  {
    label: 'Bệnh viện Châm cứu Trung ương',
    value: '1056',
    city: 'Hà Nội',
    type: 'Bộ Y tế',
    level: 'Trung ương',
  },
  {
    label: 'Bệnh viện Nội tiết Trung ương',
    value: '1081',
    city: 'Hà Nội',
    type: 'Bộ Y tế',
    level: 'Trung ương',
  },
  {
    label: 'Bệnh viện Phổi Trung ương',
    value: '1058',
    city: 'Hà Nội',
    type: 'Bộ Y tế',
    level: 'Trung ương',
  },
  {
    label: 'Bệnh viện Da liễu Trung ương',
    value: '1060',
    city: 'Hà Nội',
    type: 'Bộ Y tế',
    level: 'Trung ương',
  },
  {
    label: 'Bệnh viện Thống Nhất',
    value: '79041',
    city: 'TP. Hồ Chí Minh',
    type: 'Bộ Y tế',
    level: 'Trung ương',
  },
  {
    label: 'Bệnh viện Răng Hàm Mặt Trung ương TP. HCM',
    value: '79040',
    city: 'TP. Hồ Chí Minh',
    type: 'Bộ Y tế',
    level: 'Trung ương',
  },
  {
    label: 'Bệnh viện Quân y 175',
    value: '79049',
    city: 'TP. Hồ Chí Minh',
    type: 'Bộ Quốc phòng',
    level: 'Trung ương',
  },
  {
    label: 'Bệnh viện Quân y 103',
    value: '1016',
    city: 'Hà Nội',
    type: 'Bộ Quốc phòng',
    level: 'Trung ương',
  },
  {
    label: 'Viện Bỏng Quốc gia Lê Hữu Trác',
    value: '1042',
    city: 'Hà Nội',
    type: 'Bộ Quốc phòng',
    level: 'Trung ương',
  },
]
